version: '3.1'
services:
  server:
    build:
      context: ./
      dockerfile: ./build/server/Dockerfile
    ports:
      - 9460:9460/tcp
    volumes:
      - .:/var/www/app
      - ./build/server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build/server/nginx/app.conf:/etc/nginx/app.conf
      - ./build/server/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - app
  app:
    command: "php-fpm"
    env_file: .env
    build:
      context: ./
      dockerfile: ./build/app/Dockerfile
      args:
        SYSTEM_UID: ${SYSTEM_UID}
    volumes:
      - .:/var/www/app
      - ./build/app/php/7.2/fpm/pool.d/:/etc/php/7.2/fpm/pool.d/
